<expr> ::= <term> | <term> <opt-space> "+" <opt-space> <expr> | <term> <opt-space> "-" <opt-space> <expr>
<term> ::= <factor> | <factor> <opt-space> "*" <opt-space> <term> | <factor> <opt-space> "/" <opt-space> <term>
<factor> ::= "(" <opt-space> <expr> <opt-space> ")" | <number>
<number> ::= <digit> <number> | <digit>
<digit> ::= "0"..="9"
<opt-space> ::= " " <opt-space> | ε